### ISSUE TITLE
TypeError: Cannot read property 'rewardTokenPriceEth' of undefined

### ISSUE THREAD

**Issue by gtotradingpartners** [aave/aave-js#252]
Hi Team,

We are trying to run the sample mentioned in the Aave-js-SDK (https://aave.notion.site/Aave-Js-SDK-82d56e5190b940539cc301d8b9d16b02#e03f49d55b6f4618b9a57fbcc35f88a0)

We are getting error,
`TypeError: Cannot read property 'rewardTokenPriceEth' of undefined
    at computeUserReserveData$1 (/home/Downloads/Archive/node_modules/@aave/protocol-js/dist/protocol-js.cjs.development.js:641:78)
    at /home/Downloads/Archive/node_modules/@aave/protocol-js/dist/protocol-js.cjs.development.js:702:31
    at Array.map (<anonymous>)
    at computeRawUserSummaryData$1 (/home/Downloads/Archive/node_modules/@aave/protocol-js/dist/protocol-js.cjs.development.js:693:42)
    at Object.formatUserSummaryData$1 [as formatUserSummaryData] (/home/Downloads/Archive/node_modules/@aave/protocol-js/dist/protocol-js.cjs.development.js:752:18)
    at /home/Downloads/Archive/new_try.js:120:22
`

The actual code we tried (Excluding the functions),
`
(async ()=>{ 
let userAddress = "0x........"
const poolReservesData = (await getPoolReserveData()).reserves;
const rawUserReserves = (await getUserReserveData(userAddress)).userReserves;
let userSummary = v2.formatUserSummaryData(poolReservesData, rawUserReserves, userAddress.toLowerCase(), Math.floor(Date.now()/ 1000))
console.log(userSummary)
})();
`
Could you please help on this?

**Comment by sakulstra** [comment]
@gtotradingpartners sorry for the delayed response, we're currently working on a more modular alternative library which should be available in the coming weeks(at least as a beta).

In the meantime to solve your issue you need to provider one more parameter to formatUserSummaryData which you can find here: https://github.com/aave/aave-js/blob/master/src/v2/types.ts#L24

**Comment by tejareddy8888** [comment]
Hey @sakulstra, As mentioned above to use the 6 argument, could you also mention from where does this value are fetched how do we fetch that reward information, It is quite difficult to figure it out automatically ? I tried both in Mainnet and Kovan subgraph playground. I did not manage to have the data for me. 

Thanks in advance
